// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar(elite string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<nav class=\"navbar\"><img src=\"/images/logo-copy.png\" alt=\"Arohana Trading Academy Logo\" class=\"logo\"><div class=\"company-info\"><h1>Arohana Trading Academy</h1><p class=\"slogan\" style=\"margin-left: 10px;\">Build wealth with little intelligence and a lot of commonsense.</p></div><input type=\"checkbox\" id=\"menu-toggle\"><div class=\"hamburger-menu\" onclick=\"document.getElementById(&#39;menu-toggle&#39;).checked = !document.getElementById(&#39;menu-toggle&#39;).checked;\"><div></div><div></div><div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if elite == "true" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<ul class=\"nav-links\"><li><a href=\"/auth/news\">News</a></li><li class=\"dropdown\"><a href=\"#\">Stocks</a><div class=\"dropdown-content\"><a href=\"/auth/elite\">Elite Stocks</a> <a href=\"/auth/dashboard\">Current Stocks</a> <a href=\"/auth/pastPosts\">Past Stocks</a> <a href=\"/auth/recent-updates\">Recent Updates</a></div></li><li><a href=\"/auth/profile\">Profile</a></li></ul><div class=\"btn\"><button type=\"submit\" class=\"btn-login\" onclick=\"const cookies = document.cookie.split(&#39;;&#39;);\n                for (let c = 0; c &lt; cookies.length; c++) {\n                    const d = window.location.hostname.split(&#39;.&#39;);\n                    while (d.length &gt; 0) {\n                        const cookieBase = encodeURIComponent(cookies[c].split(&#39;;&#39;)[0].split(&#39;=&#39;)[0]) +\n                              &#39;=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain=&#39; + d.join(&#39;.&#39;) + &#39; ;path=&#39;;\n                        const p = location.pathname.split(&#39;/&#39;);\n                        document.cookie = cookieBase + &#39;/&#39;;\n                        while (p.length &gt; 0) {\n                            document.cookie = cookieBase + p.join(&#39;/&#39;);\n                            p.pop();\n                        };\n                        d.shift();\n                    }\n                }\n                window.location.href = &#39;/&#39;\">Logout</button></div><div class=\"nav-links-mobile\"><a href=\"/auth/news\">News</a> <a href=\"/auth/elite\">Elite Stocks</a> <a href=\"/auth/dashboard\">Current Stocks</a> <a href=\"/auth/past-stocks\">Past Stocks</a> <a href=\"/auth/recent-updates\">Recent Updates</a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<ul class=\"nav-links\"><li><a href=\"/auth/news\">News</a></li><li class=\"dropdown\"><a href=\"#\">Stocks</a><div class=\"dropdown-content\"><a href=\"/auth/dashboard\">Current Stocks</a> <a href=\"/auth/pastPosts\">Past Stocks</a> <a href=\"/auth/recent-updates\">Recent Updates</a></div></li><li><a href=\"/auth/profile\">Profile</a></li></ul><div class=\"btn\"><button type=\"submit\" class=\"btn-login\" onclick=\"const cookies = document.cookie.split(&#39;;&#39;);\n                for (let c = 0; c &lt; cookies.length; c++) {\n                    const d = window.location.hostname.split(&#39;.&#39;);\n                    while (d.length &gt; 0) {\n                        const cookieBase = encodeURIComponent(cookies[c].split(&#39;;&#39;)[0].split(&#39;=&#39;)[0]) +\n                              &#39;=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain=&#39; + d.join(&#39;.&#39;) + &#39; ;path=&#39;;\n                        const p = location.pathname.split(&#39;/&#39;);\n                        document.cookie = cookieBase + &#39;/&#39;;\n                        while (p.length &gt; 0) {\n                            document.cookie = cookieBase + p.join(&#39;/&#39;);\n                            p.pop();\n                        };\n                        d.shift();\n                    }\n                }\n                window.location.href = &#39;/&#39;\">Logout</button></div><div class=\"nav-links-mobile\"><a href=\"/auth/news\">News</a> <a href=\"/auth/dashboard\">Current Stocks</a> <a href=\"/auth/past-stocks\">Past Stocks</a> <a href=\"/auth/recent-updates\">Recent Updates</a> <a href=\"/auth/profile\">Profile</a></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
